---
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Add the name server on resolv conf file
      lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        state: present

    - name: Installation
      action: shell cd /opt/ && wget https://example.com

    - name: Tar unlock
      action: shell cd /opt && tar -xvf /opt/example.tar

    - name: Change Permission
      ansible.builtin.file:
        path: /opt/installer-file-script
        mode: '0777'

    - name: Run Script
      ansible.builtin.shell: /opt/installer-file-script

    - name: Remove the name server on resolv conf file
      lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        state: absent




