---
apiVersion: v1
kind: Service
metadata:
  name: drupalservice
  namespace: production
  labels:
    app: drupal
spec:
  type: NodePort
  selector:
    app: drupal
    type: front-tier
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupalpvc
  namespace: production
  label:
    app: drupal
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: production
  labels:
    app: drupal
    type: front-tier
spec:
  selector:
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      name: drupal
      labels:
        app: drupal
    spec:
     containers:
       - name: drupal
         image: drupal:latest
         ports:
           - containerPort: 30080
         volumeMounts:
           - name: drupal
             mountPath: /var/www/html/modules
             subPath: modules
           - name: drupal
             mountPath: /var/www/html/profiles
             subPath: profiles
           - name: drupal
             mountPath: /var/www/html/themes
             subPath: themes
     volumes:
       - name: drupal
         persistentVolumeClaim:
             claimName: drupalpvc