---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongoadmin
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongospace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongorule
  namespace: mongospace
rules:
 - apiGroups: [""]
   resources: ["services","persistentvolumeclaims","pods"]
   verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongobind
  namespace: mongospace
subjects:
 -  kind: ServiceAccount
    name: mongoadmin
    namespace: mongospace
roleRef:
  kind: Role
  name: mongorule
  apiGroup: rbac.authorization.k8s.io